<a href="https://colab.research.google.com/github/ajaycode/machine-learning/blob/main/sentence_transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install -U sentence-transformers
from sentence_transformers import SentenceTransformer, LoggingHandler, util
import numpy as np
import logging



model = SentenceTransformer('sentence-transformers/bert-base-nli-mean-tokens')
intent = 'I fixed the issue with a hot-patch'
other_sentences = ['This was not a bug.',
          'Refactored the code to resolve the issue.',
          'Invalid. The code works on my machine.',
          'Race-condition identified and submitted a pull request.',
          'This was not a bug, must be a False Postive.',
          'Capacity issue. Fixed by adding more clusters in the region.',
          'Transient issue.',
          'Verified. The issue exists.'
          'I fixed this by a pull request.',
          'I hot patched the issue.',
          'I turned on the heater.',
          'The developer patched the dry-wall.'
          ]

#Encode all sentences
intent_embedding = model.encode (intent)
embeddings = model.encode(other_sentences)

#Compute cosine similarity between all pairs
cos_sim = util.cos_sim( embeddings,intent_embedding)

#Add all pairs to a list with their cosine similarity score
all_sentence_combinations = []

for i in range(len(cos_sim)):
    all_sentence_combinations.append([cos_sim[i], i])

#Sort list by the highest cosine similarity score
all_sentence_combinations = sorted(all_sentence_combinations, key=lambda x: x[0], reverse=True)

print("Sentences sorted by similarity:\n")
for score, i in all_sentence_combinations:
    print (cos_sim[i], other_sentences[i])


Sentences sorted by similarity:

tensor([0.8527]) I hot patched the issue.
tensor([0.7057]) Verified. The issue exists.I fixed this by a pull request.
tensor([0.6800]) Refactored the code to resolve the issue.
tensor([0.6678]) I turned on the heater.
tensor([0.5144]) Race-condition identified and submitted a pull request.
tensor([0.5081]) The developer patched the dry-wall.
tensor([0.4464]) Invalid. The code works on my machine.
tensor([0.4329]) Capacity issue. Fixed by adding more clusters in the region.
tensor([0.4024]) This was not a bug, must be a False Postive.
tensor([0.3259]) Transient issue.
tensor([0.2517]) This was not a bug.
